**SEAN FLETCHER**
Lab 07

"###" at this point in time I am about 90% finished with Assignment 02 notebook d. The majority of code I used in this lab came from work I have already done for Assignment 02.

# <center>Lab : Decision Trees and Random Forests</center>

We use Decision Trees and Random Forests to the classify the quality of Wine from it's attributes. The wine dataset contains the results of a chemical analysis of wines grown in a specific area of Italy. Three types of wine are represented in the 178 samples, with the results of 13 chemical analyses recorded for each sample. The class label variable has been transformed into a categoric variable.

The data contains no missing values and consits of only numeric data, with a three class target variable (class label) for classification.

In [11]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score



import os
from IPython.display import Image

In [2]:
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine//wine.data', header=None)

df.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
              'Alcalinity of ash', 'Magnesium', 'Total phenols',
              'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
              'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

display(df.head())

print('# data points: %d' % df.shape[0])
print('Class labels:', np.unique(df['Class label']))

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

# data points: 178
Class labels: [1 2 3]


## Data Preperation


### Exercise
Define a variable **X** which consists of all columns except Class label and a variable **y** that has just the class label column

In [3]:
y = df['Class label']
X = df.drop('Class label',axis=1)

In [ ]:
X.head()

In [ ]:
y.head()

### Exercise
Split the data into training and test subsets. The test data should be about 20% of the total records.

In [6]:
X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=13)

## Decision Tree

### Exercise :
Use the Scikit-learn package [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) to build a decision tree for our training set. You should use the entropy for evaluating the splits and the maximum depth of the tree should be 3

In [7]:
dtree_clf = DecisionTreeClassifier(max_depth=3, random_state=13, criterion='entropy')

In [8]:
dtree_clf.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=13)


### Exercise :
Display the accuracy of your trained model on the test set

In [9]:
dtree_pred = dtree_clf.predict(X_test)


In [10]:
accuracy = accuracy_score(y_test, dtree_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9722222222222222


### Exercise :
Display the Confusion matrix, precision, recall, and f1 scores (for the later items, you may want to look at the classification report method)

In [13]:
  dtree_prec = precision_score(y_test, dtree_pred, average='weighted')
  dtree_rcll = recall_score(y_test, dtree_pred, average='weighted')
  dtree_f1 = f1_score(y_test, dtree_pred, average='weighted')
  dtree_cm = confusion_matrix(y_test, dtree_pred)

  print(dtree_cm)
  print("precision: ", dtree_prec)  #
  print("recall: ", dtree_rcll)     #
  print("f1: ", dtree_f1)           #

[[12  0  0]
 [ 0 15  0]
 [ 0  1  8]]
precision:  0.9739583333333334
recall:  0.9722222222222222
f1:  0.971853257432005


### Optional Exercise:
It can be interesting to see a visualization of the tree. To do this, you will need to follow the instructions in the book starting around Page 175. If you are doing this on your local machine, then you may need to install the graphviz package (http://www.graphviz.org/download)  The graphviz application is already installed on colab.     

If you want to display the png file in your notebook, you can put use the following code : Image(filename='./output/fig-tree.png')

## Random Forest

### Exercise :
Use the Scikit-learn package [RandomForestCassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) to build a random forest for our training set. You should use the entropy for evaluating the splits and you should create approximately 200 trees

In [14]:
rforest_clf = RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=13, n_jobs=-1)


In [15]:
rforest_clf.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=200, n_jobs=-1,
                       random_state=13)

In [17]:
rforest_pred = rforest_clf.predict(X_test)



### Exercise :
Display the accuracy of your trained model on the test set

In [18]:
accuracy = accuracy_score(y_test, rforest_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


### Exercise :
Display the Confusion matrix, precision, recall, and f1 scores (for the later items, you may want to look at the classification report method)

In [19]:
  dtree_prec = precision_score(y_test, rforest_pred, average='weighted')
  dtree_rcll = recall_score(y_test, rforest_pred, average='weighted')
  dtree_f1 = f1_score(y_test, rforest_pred, average='weighted')
  dtree_cm = confusion_matrix(y_test, rforest_pred)

  print(dtree_cm)
  print("precision: ", dtree_prec)  #
  print("recall: ", dtree_rcll)     #
  print("f1: ", dtree_f1)           #

[[12  0  0]
 [ 0 15  0]
 [ 0  0  9]]
precision:  1.0
recall:  1.0
f1:  1.0


### Exercise:
Display the features that random forest classifier found important (Pg 198 in the book)

In [20]:
rforest_feat_importance = rforest_clf.feature_importances_


In [21]:
def get_top_features(coefs, X_train_df):
  columns = X_train_df.columns

  list_of_tuples = []

  if len(coefs) == 1:
    coefs = coefs[0]

  for i in range(len(columns)):
    tup00 = (columns[i], abs(coefs[i]))
    list_of_tuples.append(tup00)

  # sort
  sorted_tupe_list = sorted(list_of_tuples, key=lambda x: x[1], reverse=True)

  return sorted_tupe_list

In [22]:
for i in get_top_features(rforest_feat_importance, X_train):
  print(i)

('Proline', 0.1664502294994846)
('Flavanoids', 0.15976401308401014)
('Color intensity', 0.15370650398927632)
('OD280/OD315 of diluted wines', 0.13008725609434)
('Alcohol', 0.11426365663146966)
('Total phenols', 0.06859146971780469)
('Hue', 0.06638430324106785)
('Magnesium', 0.032246449672365445)
('Malic acid', 0.030729693025082064)
('Proanthocyanins', 0.02937856158760024)
('Nonflavanoid phenols', 0.01895659406808127)
('Alcalinity of ash', 0.016767860253506968)
('Ash', 0.012673409135910916)
